#!/usr/bin/env bash
# Regenerate SpoolHard's custom LVGL fonts.
#
# Why we ship our own instead of LVGL's built-in montserrat fonts: the
# defaults are compiled with a minimal glyph set (0x20-0x7F + 0xB0 + 0x2022 +
# FontAwesome). We need a few extra general-punctuation chars (em-dash,
# en-dash, ellipsis) and want a single place to add more glyphs later.
#
# Output is committed under console/firmware/src/fonts/ — PlatformIO's auto-
# glob picks them up, no build-config changes needed. Re-run this script
# whenever you add a glyph to EXTRA_CHARS or FA_EXTRA_SYMBOLS.
#
# Requires: bash, curl, node + npm (ships npx).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRODUCT_DIR="$(dirname "$SCRIPT_DIR")"
SRC_FONTS_DIR="$PRODUCT_DIR/fonts"                    # source TTFs cache
OUT_FONTS_DIR="$PRODUCT_DIR/firmware/src/fonts"       # generated .c files

MONT_TTF="$SRC_FONTS_DIR/Montserrat-Medium.ttf"
FA_TTF="$SRC_FONTS_DIR/FontAwesome5-Free-Solid-900.otf"

mkdir -p "$SRC_FONTS_DIR" "$OUT_FONTS_DIR"

# ── Source TTFs ───────────────────────────────────────────────────
# Fetched once, cached under fonts/. .gitignore'd — regenerated by anyone
# who runs this script. (We don't commit TTFs because they're chunky and
# the generated .c files are what the build actually consumes.)
if [[ ! -f "$MONT_TTF" ]]; then
  echo "[fonts] downloading Montserrat-Medium.ttf"
  curl -fL -o "$MONT_TTF" \
    "https://github.com/googlefonts/montserrat/raw/master/fonts/ttf/Montserrat-Medium.ttf"
fi
if [[ ! -f "$FA_TTF" ]]; then
  echo "[fonts] downloading Font Awesome 5 Free Solid"
  curl -fL -o "$FA_TTF" \
    "https://github.com/FortAwesome/Font-Awesome/raw/5.x/otfs/Font%20Awesome%205%20Free-Solid-900.otf"
fi

# ── Glyph ranges ──────────────────────────────────────────────────
# The first three lines are LVGL's default montserrat set, so anything LVGL
# expects (bullet, degree) keeps working. EXTRA_CHARS is the SpoolHard-only
# extension — edit it and re-run this script to pick up new glyphs.
MONT_BASE="0x20-0x7F,0xB0,0x2022"
EXTRA_CHARS="0x2013,0x2014,0x2026"      # en-dash, em-dash, horizontal ellipsis
MONT_RANGE="$MONT_BASE,$EXTRA_CHARS"

# FontAwesome 5 Free Solid glyphs for the LV_SYMBOL_* macros we actually
# use, plus a curated set of likely-useful ones so adding a new LV_SYMBOL
# call in future UI code doesn't automatically require regenerating. Keeping
# this narrow trims the per-size .c file by a few KB vs. LVGL's full default
# list. Brands-only icons (USB, BLUETOOTH) are intentionally omitted — they
# live in a separate FA file we don't ship.
FA_SYMBOLS=(
  61452   # OK       (F00C)
  61453   # CLOSE    (F00D)
  61457   # POWER    (F011)
  61459   # SETTINGS (F013)
  61461   # HOME     (F015)
  61473   # REFRESH  (F021)
  61515   # PLAY     (F04B)
  61516   # PAUSE    (F04C)
  61517   # STOP     (F04D)
  61523   # LEFT     (F053)
  61524   # RIGHT    (F054)
  61543   # PLUS     (F067)
  61544   # MINUS    (F068)
  61553   # WARNING  (F071)
  61559   # UP       (F077)
  61560   # DOWN     (F078)
  61639   # SAVE     (F0C7)
  61671   # CHARGE   (F0E7)
  61931   # WIFI     (F1EB)
  62189   # TRASH    (F2ED)
  62212   # EDIT     (F304)
)
FA_RANGE=$(IFS=,; echo "${FA_SYMBOLS[*]}")

# ── Emit ──────────────────────────────────────────────────────────
SIZES=(14 16 18 22 28 36)

for size in "${SIZES[@]}"; do
  out="$OUT_FONTS_DIR/spoolhard_mont_${size}.c"
  echo "[fonts] generating $(basename "$out") (${size}px, bpp=4)"
  npx -y lv_font_conv@^1.5.2 \
    --no-compress --no-prefilter --bpp 4 --size "$size" \
    --font "$MONT_TTF" -r "$MONT_RANGE" \
    --font "$FA_TTF"   -r "$FA_RANGE" \
    --format lvgl --force-fast-kern-format \
    --lv-include lvgl.h \
    -o "$out"
done

echo
echo "Done. Generated fonts in $OUT_FONTS_DIR:"
ls -l "$OUT_FONTS_DIR"/spoolhard_mont_*.c | awk '{ printf "  %s  %s\n", $5, $9 }'
